site_name: MkDocs
site_url: https://github.com/amit-test/waveorder/
site_description: Project documentation with Markdown.
site_author: MkDocs Team

repo_url: https://github.com/waveorder/
edit_uri: blob/master/docs/

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  locale: en
  analytics: {gtag: ''}
  highlightjs: true
  hljs_languages:
    - yaml
    - django

nav:
  - Home: docs/README.md
  - API: waveorder/autoapi/
  - Getting Started: docs/README.md
  - User Guide: docs/README.md
  - Developer Guide: docs/README.md
  - About:
    - Release Notes: docs/README.md
    - Contributing: docs/README.md
    - License: docs/README.md

extra_css:
  - css/extra.css

exclude_docs: |

markdown_extensions:
  - toc:
      permalink: 
  - attr_list
  - def_list
  - tables
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.snippets
  - pymdownx.superfences
  - callouts
  - mdx_gh_links:
      user: mkdocs
      repo: mkdocs
  - mkdocs-click

copyright: Copyright &copy; 2025.

hooks:
  - docs/examples/test.py

plugins:
  - search
  - gen-files:
      scripts:
        - docs/examples/gen_ref_pages.py
  - redirects:
      redirect_maps:
        user-guide/plugins.md: docs/README.md
        user-guide/custom-themes.md: docs/README.md
        user-guide/styling-your-docs.md: docs/README.md
  - autorefs
  - literate-nav:
      nav_file: README.md
      implicit_index: true
  - mkdocs-autoapi:
      autoapi_dir: waveorder/autoapi
      autoapi_add_nav_entry: Reference
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: list
            members_order: source
            show_root_heading: true
            show_source: false
            show_signature_annotations: true
          paths: [waveorder] # Adjust this to the path of your Python source code

watch:
  - waveorder
